/* automatically generated by rust-bindgen 0.72.1 */

#[doc = r" If Bindgen could only determine the size and alignment of a"]
#[doc = r" type, it is represented like this."]
#[derive(PartialEq, Copy, Clone, Debug, Hash)]
#[repr(C)]
pub struct __BindgenOpaqueArray<T: Copy, const N: usize>(pub [T; N]);
impl<T: Copy + Default, const N: usize> Default for __BindgenOpaqueArray<T, N> {
    fn default() -> Self {
        Self([<T as Default>::default(); N])
    }
}
#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const RULE_FLAGS_NULL: u32 = 4;
pub const STRING_FLAGS_LAST_IN_RULE: u32 = 4096;
pub const META_TYPE_INTEGER: u32 = 1;
pub const META_TYPE_STRING: u32 = 2;
pub const META_TYPE_BOOLEAN: u32 = 3;
pub const META_FLAGS_LAST_IN_RULE: u32 = 1;
pub const YARA_ERROR_LEVEL_ERROR: u32 = 0;
pub const YARA_ERROR_LEVEL_WARNING: u32 = 1;
pub const ERROR_SUCCESS: u32 = 0;
pub const ERROR_INSUFICIENT_MEMORY: u32 = 1;
pub const ERROR_INSUFFICIENT_MEMORY: u32 = 1;
pub const ERROR_COULD_NOT_ATTACH_TO_PROCESS: u32 = 2;
pub const ERROR_COULD_NOT_OPEN_FILE: u32 = 3;
pub const ERROR_COULD_NOT_MAP_FILE: u32 = 4;
pub const ERROR_INVALID_FILE: u32 = 6;
pub const ERROR_CORRUPT_FILE: u32 = 7;
pub const ERROR_UNSUPPORTED_FILE_VERSION: u32 = 8;
pub const ERROR_INVALID_REGULAR_EXPRESSION: u32 = 9;
pub const ERROR_INVALID_HEX_STRING: u32 = 10;
pub const ERROR_SYNTAX_ERROR: u32 = 11;
pub const ERROR_LOOP_NESTING_LIMIT_EXCEEDED: u32 = 12;
pub const ERROR_DUPLICATED_LOOP_IDENTIFIER: u32 = 13;
pub const ERROR_DUPLICATED_IDENTIFIER: u32 = 14;
pub const ERROR_DUPLICATED_TAG_IDENTIFIER: u32 = 15;
pub const ERROR_DUPLICATED_META_IDENTIFIER: u32 = 16;
pub const ERROR_DUPLICATED_STRING_IDENTIFIER: u32 = 17;
pub const ERROR_UNREFERENCED_STRING: u32 = 18;
pub const ERROR_UNDEFINED_STRING: u32 = 19;
pub const ERROR_UNDEFINED_IDENTIFIER: u32 = 20;
pub const ERROR_MISPLACED_ANONYMOUS_STRING: u32 = 21;
pub const ERROR_INCLUDES_CIRCULAR_REFERENCE: u32 = 22;
pub const ERROR_INCLUDE_DEPTH_EXCEEDED: u32 = 23;
pub const ERROR_WRONG_TYPE: u32 = 24;
pub const ERROR_EXEC_STACK_OVERFLOW: u32 = 25;
pub const ERROR_SCAN_TIMEOUT: u32 = 26;
pub const ERROR_TOO_MANY_SCAN_THREADS: u32 = 27;
pub const ERROR_CALLBACK_ERROR: u32 = 28;
pub const ERROR_INVALID_ARGUMENT: u32 = 29;
pub const ERROR_TOO_MANY_MATCHES: u32 = 30;
pub const ERROR_INTERNAL_FATAL_ERROR: u32 = 31;
pub const ERROR_NESTED_FOR_OF_LOOP: u32 = 32;
pub const ERROR_INVALID_FIELD_NAME: u32 = 33;
pub const ERROR_UNKNOWN_MODULE: u32 = 34;
pub const ERROR_NOT_A_STRUCTURE: u32 = 35;
pub const ERROR_NOT_INDEXABLE: u32 = 36;
pub const ERROR_NOT_A_FUNCTION: u32 = 37;
pub const ERROR_INVALID_FORMAT: u32 = 38;
pub const ERROR_TOO_MANY_ARGUMENTS: u32 = 39;
pub const ERROR_WRONG_ARGUMENTS: u32 = 40;
pub const ERROR_WRONG_RETURN_TYPE: u32 = 41;
pub const ERROR_DUPLICATED_STRUCTURE_MEMBER: u32 = 42;
pub const ERROR_EMPTY_STRING: u32 = 43;
pub const ERROR_DIVISION_BY_ZERO: u32 = 44;
pub const ERROR_REGULAR_EXPRESSION_TOO_LARGE: u32 = 45;
pub const ERROR_TOO_MANY_RE_FIBERS: u32 = 46;
pub const ERROR_COULD_NOT_READ_PROCESS_MEMORY: u32 = 47;
pub const ERROR_INVALID_EXTERNAL_VARIABLE_TYPE: u32 = 48;
pub const ERROR_REGULAR_EXPRESSION_TOO_COMPLEX: u32 = 49;
pub const ERROR_INVALID_MODULE_NAME: u32 = 50;
pub const ERROR_TOO_MANY_STRINGS: u32 = 51;
pub const ERROR_INTEGER_OVERFLOW: u32 = 52;
pub const ERROR_CALLBACK_REQUIRED: u32 = 53;
pub const ERROR_INVALID_OPERAND: u32 = 54;
pub const ERROR_COULD_NOT_READ_FILE: u32 = 55;
pub const ERROR_DUPLICATED_EXTERNAL_VARIABLE: u32 = 56;
pub const ERROR_INVALID_MODULE_DATA: u32 = 57;
pub const ERROR_WRITING_FILE: u32 = 58;
pub const ERROR_INVALID_MODIFIER: u32 = 59;
pub const ERROR_DUPLICATED_MODIFIER: u32 = 60;
pub const ERROR_BLOCK_NOT_READY: u32 = 61;
pub const ERROR_INVALID_PERCENTAGE: u32 = 62;
pub const ERROR_IDENTIFIER_MATCHES_WILDCARD: u32 = 63;
pub const ERROR_INVALID_VALUE: u32 = 64;
pub const ERROR_TOO_SLOW_SCANNING: u32 = 65;
pub const ERROR_UNKNOWN_ESCAPE_SEQUENCE: u32 = 66;
pub const CALLBACK_MSG_RULE_MATCHING: u32 = 1;
pub const CALLBACK_MSG_RULE_NOT_MATCHING: u32 = 2;
pub const CALLBACK_MSG_SCAN_FINISHED: u32 = 3;
pub const CALLBACK_MSG_IMPORT_MODULE: u32 = 4;
pub const CALLBACK_MSG_MODULE_IMPORTED: u32 = 5;
pub const CALLBACK_MSG_TOO_MANY_MATCHES: u32 = 6;
pub const CALLBACK_MSG_CONSOLE_LOG: u32 = 7;
pub const CALLBACK_MSG_TOO_SLOW_SCANNING: u32 = 8;
pub const CALLBACK_CONTINUE: u32 = 0;
pub const CALLBACK_ABORT: u32 = 1;
pub const CALLBACK_ERROR: u32 = 2;
pub const SCAN_FLAGS_FAST_MODE: u32 = 1;
pub const SCAN_FLAGS_PROCESS_MEMORY: u32 = 2;
pub const SCAN_FLAGS_NO_TRYCATCH: u32 = 4;
pub const SCAN_FLAGS_REPORT_RULES_MATCHING: u32 = 8;
pub const SCAN_FLAGS_REPORT_RULES_NOT_MATCHING: u32 = 16;
pub const YR_UNDEFINED: i64 = -1483400188077313;
pub const OBJECT_TYPE_INTEGER: u32 = 1;
pub const OBJECT_TYPE_STRING: u32 = 2;
pub const OBJECT_TYPE_STRUCTURE: u32 = 3;
pub const OBJECT_TYPE_ARRAY: u32 = 4;
pub const OBJECT_TYPE_FUNCTION: u32 = 5;
pub const OBJECT_TYPE_DICTIONARY: u32 = 6;
pub const OBJECT_TYPE_FLOAT: u32 = 7;
pub type jmp_buf = [::std::os::raw::c_int; 48usize];
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_off_t = __int64_t;
pub type size_t = __darwin_size_t;
pub type fpos_t = __darwin_off_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sbuf {
    pub _base: *mut ::std::os::raw::c_uchar,
    pub _size: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __sbuf"][::std::mem::size_of::<__sbuf>() - 16usize];
    ["Alignment of __sbuf"][::std::mem::align_of::<__sbuf>() - 8usize];
    ["Offset of field: __sbuf::_base"][::std::mem::offset_of!(__sbuf, _base) - 0usize];
    ["Offset of field: __sbuf::_size"][::std::mem::offset_of!(__sbuf, _size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILEX {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILE {
    pub _p: *mut ::std::os::raw::c_uchar,
    pub _r: ::std::os::raw::c_int,
    pub _w: ::std::os::raw::c_int,
    pub _flags: ::std::os::raw::c_short,
    pub _file: ::std::os::raw::c_short,
    pub _bf: __sbuf,
    pub _lbfsize: ::std::os::raw::c_int,
    pub _cookie: *mut ::std::os::raw::c_void,
    pub _close: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub _read: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *mut ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _seek: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: fpos_t,
            arg3: ::std::os::raw::c_int,
        ) -> fpos_t,
    >,
    pub _write: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _ub: __sbuf,
    pub _extra: *mut __sFILEX,
    pub _ur: ::std::os::raw::c_int,
    pub _ubuf: [::std::os::raw::c_uchar; 3usize],
    pub _nbuf: [::std::os::raw::c_uchar; 1usize],
    pub _lb: __sbuf,
    pub _blksize: ::std::os::raw::c_int,
    pub _offset: fpos_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __sFILE"][::std::mem::size_of::<__sFILE>() - 152usize];
    ["Alignment of __sFILE"][::std::mem::align_of::<__sFILE>() - 8usize];
    ["Offset of field: __sFILE::_p"][::std::mem::offset_of!(__sFILE, _p) - 0usize];
    ["Offset of field: __sFILE::_r"][::std::mem::offset_of!(__sFILE, _r) - 8usize];
    ["Offset of field: __sFILE::_w"][::std::mem::offset_of!(__sFILE, _w) - 12usize];
    ["Offset of field: __sFILE::_flags"][::std::mem::offset_of!(__sFILE, _flags) - 16usize];
    ["Offset of field: __sFILE::_file"][::std::mem::offset_of!(__sFILE, _file) - 18usize];
    ["Offset of field: __sFILE::_bf"][::std::mem::offset_of!(__sFILE, _bf) - 24usize];
    ["Offset of field: __sFILE::_lbfsize"][::std::mem::offset_of!(__sFILE, _lbfsize) - 40usize];
    ["Offset of field: __sFILE::_cookie"][::std::mem::offset_of!(__sFILE, _cookie) - 48usize];
    ["Offset of field: __sFILE::_close"][::std::mem::offset_of!(__sFILE, _close) - 56usize];
    ["Offset of field: __sFILE::_read"][::std::mem::offset_of!(__sFILE, _read) - 64usize];
    ["Offset of field: __sFILE::_seek"][::std::mem::offset_of!(__sFILE, _seek) - 72usize];
    ["Offset of field: __sFILE::_write"][::std::mem::offset_of!(__sFILE, _write) - 80usize];
    ["Offset of field: __sFILE::_ub"][::std::mem::offset_of!(__sFILE, _ub) - 88usize];
    ["Offset of field: __sFILE::_extra"][::std::mem::offset_of!(__sFILE, _extra) - 104usize];
    ["Offset of field: __sFILE::_ur"][::std::mem::offset_of!(__sFILE, _ur) - 112usize];
    ["Offset of field: __sFILE::_ubuf"][::std::mem::offset_of!(__sFILE, _ubuf) - 116usize];
    ["Offset of field: __sFILE::_nbuf"][::std::mem::offset_of!(__sFILE, _nbuf) - 119usize];
    ["Offset of field: __sFILE::_lb"][::std::mem::offset_of!(__sFILE, _lb) - 120usize];
    ["Offset of field: __sFILE::_blksize"][::std::mem::offset_of!(__sFILE, _blksize) - 136usize];
    ["Offset of field: __sFILE::_offset"][::std::mem::offset_of!(__sFILE, _offset) - 144usize];
};
pub type FILE = __sFILE;
pub type YR_STREAM_READ_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        ptr: *mut ::std::os::raw::c_void,
        size: size_t,
        count: size_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> size_t,
>;
pub type YR_STREAM_WRITE_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        ptr: *const ::std::os::raw::c_void,
        size: size_t,
        count: size_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> size_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _YR_STREAM {
    pub user_data: *mut ::std::os::raw::c_void,
    pub read: YR_STREAM_READ_FUNC,
    pub write: YR_STREAM_WRITE_FUNC,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _YR_STREAM"][::std::mem::size_of::<_YR_STREAM>() - 24usize];
    ["Alignment of _YR_STREAM"][::std::mem::align_of::<_YR_STREAM>() - 8usize];
    ["Offset of field: _YR_STREAM::user_data"]
        [::std::mem::offset_of!(_YR_STREAM, user_data) - 0usize];
    ["Offset of field: _YR_STREAM::read"][::std::mem::offset_of!(_YR_STREAM, read) - 8usize];
    ["Offset of field: _YR_STREAM::write"][::std::mem::offset_of!(_YR_STREAM, write) - 16usize];
};
pub type YR_STREAM = _YR_STREAM;
pub type yr_arena_off_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_ARENA_REF {
    pub buffer_id: u32,
    pub offset: yr_arena_off_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ARENA_REF"][::std::mem::size_of::<YR_ARENA_REF>() - 8usize];
    ["Alignment of YR_ARENA_REF"][::std::mem::align_of::<YR_ARENA_REF>() - 4usize];
    ["Offset of field: YR_ARENA_REF::buffer_id"]
        [::std::mem::offset_of!(YR_ARENA_REF, buffer_id) - 0usize];
    ["Offset of field: YR_ARENA_REF::offset"]
        [::std::mem::offset_of!(YR_ARENA_REF, offset) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_ARENA_BUFFER {
    pub data: *mut u8,
    pub size: size_t,
    pub used: size_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ARENA_BUFFER"][::std::mem::size_of::<YR_ARENA_BUFFER>() - 24usize];
    ["Alignment of YR_ARENA_BUFFER"][::std::mem::align_of::<YR_ARENA_BUFFER>() - 8usize];
    ["Offset of field: YR_ARENA_BUFFER::data"]
        [::std::mem::offset_of!(YR_ARENA_BUFFER, data) - 0usize];
    ["Offset of field: YR_ARENA_BUFFER::size"]
        [::std::mem::offset_of!(YR_ARENA_BUFFER, size) - 8usize];
    ["Offset of field: YR_ARENA_BUFFER::used"]
        [::std::mem::offset_of!(YR_ARENA_BUFFER, used) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_RELOC {
    pub buffer_id: u32,
    pub offset: yr_arena_off_t,
    pub next: *mut YR_RELOC,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RELOC"][::std::mem::size_of::<YR_RELOC>() - 16usize];
    ["Alignment of YR_RELOC"][::std::mem::align_of::<YR_RELOC>() - 8usize];
    ["Offset of field: YR_RELOC::buffer_id"][::std::mem::offset_of!(YR_RELOC, buffer_id) - 0usize];
    ["Offset of field: YR_RELOC::offset"][::std::mem::offset_of!(YR_RELOC, offset) - 4usize];
    ["Offset of field: YR_RELOC::next"][::std::mem::offset_of!(YR_RELOC, next) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_ARENA {
    pub xrefs: u32,
    pub num_buffers: u32,
    pub buffers: [YR_ARENA_BUFFER; 16usize],
    pub initial_buffer_size: size_t,
    pub reloc_list_head: *mut YR_RELOC,
    pub reloc_list_tail: *mut YR_RELOC,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ARENA"][::std::mem::size_of::<YR_ARENA>() - 416usize];
    ["Alignment of YR_ARENA"][::std::mem::align_of::<YR_ARENA>() - 8usize];
    ["Offset of field: YR_ARENA::xrefs"][::std::mem::offset_of!(YR_ARENA, xrefs) - 0usize];
    ["Offset of field: YR_ARENA::num_buffers"]
        [::std::mem::offset_of!(YR_ARENA, num_buffers) - 4usize];
    ["Offset of field: YR_ARENA::buffers"][::std::mem::offset_of!(YR_ARENA, buffers) - 8usize];
    ["Offset of field: YR_ARENA::initial_buffer_size"]
        [::std::mem::offset_of!(YR_ARENA, initial_buffer_size) - 392usize];
    ["Offset of field: YR_ARENA::reloc_list_head"]
        [::std::mem::offset_of!(YR_ARENA, reloc_list_head) - 400usize];
    ["Offset of field: YR_ARENA::reloc_list_tail"]
        [::std::mem::offset_of!(YR_ARENA, reloc_list_tail) - 408usize];
};
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _SIZED_STRING {
    pub length: u32,
    pub flags: u32,
    pub c_string: [::std::os::raw::c_char; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _SIZED_STRING"][::std::mem::size_of::<_SIZED_STRING>() - 9usize];
    ["Alignment of _SIZED_STRING"][::std::mem::align_of::<_SIZED_STRING>() - 1usize];
    ["Offset of field: _SIZED_STRING::length"]
        [::std::mem::offset_of!(_SIZED_STRING, length) - 0usize];
    ["Offset of field: _SIZED_STRING::flags"]
        [::std::mem::offset_of!(_SIZED_STRING, flags) - 4usize];
    ["Offset of field: _SIZED_STRING::c_string"]
        [::std::mem::offset_of!(_SIZED_STRING, c_string) - 8usize];
};
pub type SIZED_STRING = _SIZED_STRING;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _YR_HASH_TABLE_ENTRY {
    pub key: *mut ::std::os::raw::c_void,
    pub key_length: size_t,
    pub ns: *mut ::std::os::raw::c_char,
    pub value: *mut ::std::os::raw::c_void,
    pub next: *mut _YR_HASH_TABLE_ENTRY,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _YR_HASH_TABLE_ENTRY"][::std::mem::size_of::<_YR_HASH_TABLE_ENTRY>() - 40usize];
    ["Alignment of _YR_HASH_TABLE_ENTRY"][::std::mem::align_of::<_YR_HASH_TABLE_ENTRY>() - 8usize];
    ["Offset of field: _YR_HASH_TABLE_ENTRY::key"]
        [::std::mem::offset_of!(_YR_HASH_TABLE_ENTRY, key) - 0usize];
    ["Offset of field: _YR_HASH_TABLE_ENTRY::key_length"]
        [::std::mem::offset_of!(_YR_HASH_TABLE_ENTRY, key_length) - 8usize];
    ["Offset of field: _YR_HASH_TABLE_ENTRY::ns"]
        [::std::mem::offset_of!(_YR_HASH_TABLE_ENTRY, ns) - 16usize];
    ["Offset of field: _YR_HASH_TABLE_ENTRY::value"]
        [::std::mem::offset_of!(_YR_HASH_TABLE_ENTRY, value) - 24usize];
    ["Offset of field: _YR_HASH_TABLE_ENTRY::next"]
        [::std::mem::offset_of!(_YR_HASH_TABLE_ENTRY, next) - 32usize];
};
pub type YR_HASH_TABLE_ENTRY = _YR_HASH_TABLE_ENTRY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _YR_HASH_TABLE {
    pub size: ::std::os::raw::c_int,
    pub buckets: [*mut YR_HASH_TABLE_ENTRY; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _YR_HASH_TABLE"][::std::mem::size_of::<_YR_HASH_TABLE>() - 16usize];
    ["Alignment of _YR_HASH_TABLE"][::std::mem::align_of::<_YR_HASH_TABLE>() - 8usize];
    ["Offset of field: _YR_HASH_TABLE::size"]
        [::std::mem::offset_of!(_YR_HASH_TABLE, size) - 0usize];
    ["Offset of field: _YR_HASH_TABLE::buckets"]
        [::std::mem::offset_of!(_YR_HASH_TABLE, buckets) - 8usize];
};
pub type YR_HASH_TABLE = _YR_HASH_TABLE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mach_timebase_info {
    pub numer: u32,
    pub denom: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mach_timebase_info"][::std::mem::size_of::<mach_timebase_info>() - 8usize];
    ["Alignment of mach_timebase_info"][::std::mem::align_of::<mach_timebase_info>() - 4usize];
    ["Offset of field: mach_timebase_info::numer"]
        [::std::mem::offset_of!(mach_timebase_info, numer) - 0usize];
    ["Offset of field: mach_timebase_info::denom"]
        [::std::mem::offset_of!(mach_timebase_info, denom) - 4usize];
};
pub type mach_timebase_info_data_t = mach_timebase_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _YR_STOPWATCH {
    pub timebase: mach_timebase_info_data_t,
    pub start: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _YR_STOPWATCH"][::std::mem::size_of::<_YR_STOPWATCH>() - 16usize];
    ["Alignment of _YR_STOPWATCH"][::std::mem::align_of::<_YR_STOPWATCH>() - 8usize];
    ["Offset of field: _YR_STOPWATCH::timebase"]
        [::std::mem::offset_of!(_YR_STOPWATCH, timebase) - 0usize];
    ["Offset of field: _YR_STOPWATCH::start"]
        [::std::mem::offset_of!(_YR_STOPWATCH, start) - 8usize];
};
pub type YR_STOPWATCH = _YR_STOPWATCH;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_NOTEBOOK {
    _unused: [u8; 0],
}
pub type YR_AC_TRANSITION = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_NAMESPACE {
    pub __bindgen_anon_1: YR_NAMESPACE__bindgen_ty_1,
    pub idx: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_NAMESPACE__bindgen_ty_1 {
    pub name: *const ::std::os::raw::c_char,
    pub name_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_NAMESPACE__bindgen_ty_1"]
        [::std::mem::size_of::<YR_NAMESPACE__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_NAMESPACE__bindgen_ty_1"]
        [::std::mem::align_of::<YR_NAMESPACE__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_NAMESPACE__bindgen_ty_1::name"]
        [::std::mem::offset_of!(YR_NAMESPACE__bindgen_ty_1, name) - 0usize];
    ["Offset of field: YR_NAMESPACE__bindgen_ty_1::name_"]
        [::std::mem::offset_of!(YR_NAMESPACE__bindgen_ty_1, name_) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_NAMESPACE"][::std::mem::size_of::<YR_NAMESPACE>() - 16usize];
    ["Alignment of YR_NAMESPACE"][::std::mem::align_of::<YR_NAMESPACE>() - 8usize];
    ["Offset of field: YR_NAMESPACE::idx"][::std::mem::offset_of!(YR_NAMESPACE, idx) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_META {
    pub __bindgen_anon_1: YR_META__bindgen_ty_1,
    pub __bindgen_anon_2: YR_META__bindgen_ty_2,
    pub integer: i64,
    pub type_: i32,
    pub flags: i32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_META__bindgen_ty_1 {
    pub identifier: *const ::std::os::raw::c_char,
    pub identifier_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_META__bindgen_ty_1"][::std::mem::size_of::<YR_META__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_META__bindgen_ty_1"]
        [::std::mem::align_of::<YR_META__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_META__bindgen_ty_1::identifier"]
        [::std::mem::offset_of!(YR_META__bindgen_ty_1, identifier) - 0usize];
    ["Offset of field: YR_META__bindgen_ty_1::identifier_"]
        [::std::mem::offset_of!(YR_META__bindgen_ty_1, identifier_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_META__bindgen_ty_2 {
    pub string: *const ::std::os::raw::c_char,
    pub string_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_META__bindgen_ty_2"][::std::mem::size_of::<YR_META__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_META__bindgen_ty_2"]
        [::std::mem::align_of::<YR_META__bindgen_ty_2>() - 8usize];
    ["Offset of field: YR_META__bindgen_ty_2::string"]
        [::std::mem::offset_of!(YR_META__bindgen_ty_2, string) - 0usize];
    ["Offset of field: YR_META__bindgen_ty_2::string_"]
        [::std::mem::offset_of!(YR_META__bindgen_ty_2, string_) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_META"][::std::mem::size_of::<YR_META>() - 32usize];
    ["Alignment of YR_META"][::std::mem::align_of::<YR_META>() - 8usize];
    ["Offset of field: YR_META::integer"][::std::mem::offset_of!(YR_META, integer) - 16usize];
    ["Offset of field: YR_META::type_"][::std::mem::offset_of!(YR_META, type_) - 24usize];
    ["Offset of field: YR_META::flags"][::std::mem::offset_of!(YR_META, flags) - 28usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_STRING {
    pub flags: u32,
    pub idx: u32,
    pub fixed_offset: i64,
    pub rule_idx: u32,
    pub length: i32,
    pub __bindgen_anon_1: YR_STRING__bindgen_ty_1,
    pub __bindgen_anon_2: YR_STRING__bindgen_ty_2,
    pub chain_gap_min: i32,
    pub chain_gap_max: i32,
    pub __bindgen_anon_3: YR_STRING__bindgen_ty_3,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_STRING__bindgen_ty_1 {
    pub string: *mut u8,
    pub string_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRING__bindgen_ty_1"][::std::mem::size_of::<YR_STRING__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_STRING__bindgen_ty_1"]
        [::std::mem::align_of::<YR_STRING__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_STRING__bindgen_ty_1::string"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_1, string) - 0usize];
    ["Offset of field: YR_STRING__bindgen_ty_1::string_"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_1, string_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_STRING__bindgen_ty_2 {
    pub chained_to: *mut YR_STRING,
    pub chained_to_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRING__bindgen_ty_2"][::std::mem::size_of::<YR_STRING__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_STRING__bindgen_ty_2"]
        [::std::mem::align_of::<YR_STRING__bindgen_ty_2>() - 8usize];
    ["Offset of field: YR_STRING__bindgen_ty_2::chained_to"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_2, chained_to) - 0usize];
    ["Offset of field: YR_STRING__bindgen_ty_2::chained_to_"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_2, chained_to_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_STRING__bindgen_ty_3 {
    pub identifier: *const ::std::os::raw::c_char,
    pub identifier_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRING__bindgen_ty_3"][::std::mem::size_of::<YR_STRING__bindgen_ty_3>() - 8usize];
    ["Alignment of YR_STRING__bindgen_ty_3"]
        [::std::mem::align_of::<YR_STRING__bindgen_ty_3>() - 8usize];
    ["Offset of field: YR_STRING__bindgen_ty_3::identifier"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_3, identifier) - 0usize];
    ["Offset of field: YR_STRING__bindgen_ty_3::identifier_"]
        [::std::mem::offset_of!(YR_STRING__bindgen_ty_3, identifier_) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRING"][::std::mem::size_of::<YR_STRING>() - 56usize];
    ["Alignment of YR_STRING"][::std::mem::align_of::<YR_STRING>() - 8usize];
    ["Offset of field: YR_STRING::flags"][::std::mem::offset_of!(YR_STRING, flags) - 0usize];
    ["Offset of field: YR_STRING::idx"][::std::mem::offset_of!(YR_STRING, idx) - 4usize];
    ["Offset of field: YR_STRING::fixed_offset"]
        [::std::mem::offset_of!(YR_STRING, fixed_offset) - 8usize];
    ["Offset of field: YR_STRING::rule_idx"][::std::mem::offset_of!(YR_STRING, rule_idx) - 16usize];
    ["Offset of field: YR_STRING::length"][::std::mem::offset_of!(YR_STRING, length) - 20usize];
    ["Offset of field: YR_STRING::chain_gap_min"]
        [::std::mem::offset_of!(YR_STRING, chain_gap_min) - 40usize];
    ["Offset of field: YR_STRING::chain_gap_max"]
        [::std::mem::offset_of!(YR_STRING, chain_gap_max) - 44usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_RULE {
    pub flags: i32,
    pub num_atoms: i32,
    pub required_strings: u32,
    pub unused: u32,
    pub __bindgen_anon_1: YR_RULE__bindgen_ty_1,
    pub __bindgen_anon_2: YR_RULE__bindgen_ty_2,
    pub __bindgen_anon_3: YR_RULE__bindgen_ty_3,
    pub __bindgen_anon_4: YR_RULE__bindgen_ty_4,
    pub __bindgen_anon_5: YR_RULE__bindgen_ty_5,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULE__bindgen_ty_1 {
    pub identifier: *const ::std::os::raw::c_char,
    pub identifier_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE__bindgen_ty_1"][::std::mem::size_of::<YR_RULE__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_RULE__bindgen_ty_1"]
        [::std::mem::align_of::<YR_RULE__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_RULE__bindgen_ty_1::identifier"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_1, identifier) - 0usize];
    ["Offset of field: YR_RULE__bindgen_ty_1::identifier_"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_1, identifier_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULE__bindgen_ty_2 {
    pub tags: *const ::std::os::raw::c_char,
    pub tags_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE__bindgen_ty_2"][::std::mem::size_of::<YR_RULE__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_RULE__bindgen_ty_2"]
        [::std::mem::align_of::<YR_RULE__bindgen_ty_2>() - 8usize];
    ["Offset of field: YR_RULE__bindgen_ty_2::tags"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_2, tags) - 0usize];
    ["Offset of field: YR_RULE__bindgen_ty_2::tags_"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_2, tags_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULE__bindgen_ty_3 {
    pub metas: *mut YR_META,
    pub metas_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE__bindgen_ty_3"][::std::mem::size_of::<YR_RULE__bindgen_ty_3>() - 8usize];
    ["Alignment of YR_RULE__bindgen_ty_3"]
        [::std::mem::align_of::<YR_RULE__bindgen_ty_3>() - 8usize];
    ["Offset of field: YR_RULE__bindgen_ty_3::metas"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_3, metas) - 0usize];
    ["Offset of field: YR_RULE__bindgen_ty_3::metas_"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_3, metas_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULE__bindgen_ty_4 {
    pub strings: *mut YR_STRING,
    pub strings_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE__bindgen_ty_4"][::std::mem::size_of::<YR_RULE__bindgen_ty_4>() - 8usize];
    ["Alignment of YR_RULE__bindgen_ty_4"]
        [::std::mem::align_of::<YR_RULE__bindgen_ty_4>() - 8usize];
    ["Offset of field: YR_RULE__bindgen_ty_4::strings"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_4, strings) - 0usize];
    ["Offset of field: YR_RULE__bindgen_ty_4::strings_"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_4, strings_) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULE__bindgen_ty_5 {
    pub ns: *mut YR_NAMESPACE,
    pub ns_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE__bindgen_ty_5"][::std::mem::size_of::<YR_RULE__bindgen_ty_5>() - 8usize];
    ["Alignment of YR_RULE__bindgen_ty_5"]
        [::std::mem::align_of::<YR_RULE__bindgen_ty_5>() - 8usize];
    ["Offset of field: YR_RULE__bindgen_ty_5::ns"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_5, ns) - 0usize];
    ["Offset of field: YR_RULE__bindgen_ty_5::ns_"]
        [::std::mem::offset_of!(YR_RULE__bindgen_ty_5, ns_) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE"][::std::mem::size_of::<YR_RULE>() - 56usize];
    ["Alignment of YR_RULE"][::std::mem::align_of::<YR_RULE>() - 8usize];
    ["Offset of field: YR_RULE::flags"][::std::mem::offset_of!(YR_RULE, flags) - 0usize];
    ["Offset of field: YR_RULE::num_atoms"][::std::mem::offset_of!(YR_RULE, num_atoms) - 4usize];
    ["Offset of field: YR_RULE::required_strings"]
        [::std::mem::offset_of!(YR_RULE, required_strings) - 8usize];
    ["Offset of field: YR_RULE::unused"][::std::mem::offset_of!(YR_RULE, unused) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_EXTERNAL_VARIABLE {
    pub type_: i32,
    pub value: YR_EXTERNAL_VARIABLE__bindgen_ty_1,
    pub __bindgen_anon_1: YR_EXTERNAL_VARIABLE__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_EXTERNAL_VARIABLE__bindgen_ty_1 {
    pub i: i64,
    pub f: f64,
    pub s: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_EXTERNAL_VARIABLE__bindgen_ty_1"]
        [::std::mem::size_of::<YR_EXTERNAL_VARIABLE__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_EXTERNAL_VARIABLE__bindgen_ty_1"]
        [::std::mem::align_of::<YR_EXTERNAL_VARIABLE__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE__bindgen_ty_1::i"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE__bindgen_ty_1, i) - 0usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE__bindgen_ty_1::f"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE__bindgen_ty_1, f) - 0usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE__bindgen_ty_1::s"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE__bindgen_ty_1, s) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_EXTERNAL_VARIABLE__bindgen_ty_2 {
    pub identifier: *const ::std::os::raw::c_char,
    pub identifier_: YR_ARENA_REF,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_EXTERNAL_VARIABLE__bindgen_ty_2"]
        [::std::mem::size_of::<YR_EXTERNAL_VARIABLE__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_EXTERNAL_VARIABLE__bindgen_ty_2"]
        [::std::mem::align_of::<YR_EXTERNAL_VARIABLE__bindgen_ty_2>() - 8usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE__bindgen_ty_2::identifier"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE__bindgen_ty_2, identifier) - 0usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE__bindgen_ty_2::identifier_"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE__bindgen_ty_2, identifier_) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_EXTERNAL_VARIABLE"][::std::mem::size_of::<YR_EXTERNAL_VARIABLE>() - 24usize];
    ["Alignment of YR_EXTERNAL_VARIABLE"][::std::mem::align_of::<YR_EXTERNAL_VARIABLE>() - 8usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE::type_"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE, type_) - 0usize];
    ["Offset of field: YR_EXTERNAL_VARIABLE::value"]
        [::std::mem::offset_of!(YR_EXTERNAL_VARIABLE, value) - 8usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct YR_AC_MATCH {
    pub _bindgen_opaque_blob: [u64; 5usize],
}
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union YR_AC_MATCH__bindgen_ty_1 {
    pub _bindgen_opaque_blob: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_MATCH__bindgen_ty_1"]
        [::std::mem::size_of::<YR_AC_MATCH__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_AC_MATCH__bindgen_ty_1"]
        [::std::mem::align_of::<YR_AC_MATCH__bindgen_ty_1>() - 8usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union YR_AC_MATCH__bindgen_ty_2 {
    pub _bindgen_opaque_blob: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_MATCH__bindgen_ty_2"]
        [::std::mem::size_of::<YR_AC_MATCH__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_AC_MATCH__bindgen_ty_2"]
        [::std::mem::align_of::<YR_AC_MATCH__bindgen_ty_2>() - 8usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union YR_AC_MATCH__bindgen_ty_3 {
    pub _bindgen_opaque_blob: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_MATCH__bindgen_ty_3"]
        [::std::mem::size_of::<YR_AC_MATCH__bindgen_ty_3>() - 8usize];
    ["Alignment of YR_AC_MATCH__bindgen_ty_3"]
        [::std::mem::align_of::<YR_AC_MATCH__bindgen_ty_3>() - 8usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union YR_AC_MATCH__bindgen_ty_4 {
    pub _bindgen_opaque_blob: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_MATCH__bindgen_ty_4"]
        [::std::mem::size_of::<YR_AC_MATCH__bindgen_ty_4>() - 8usize];
    ["Alignment of YR_AC_MATCH__bindgen_ty_4"]
        [::std::mem::align_of::<YR_AC_MATCH__bindgen_ty_4>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_MATCH"][::std::mem::size_of::<YR_AC_MATCH>() - 40usize];
    ["Alignment of YR_AC_MATCH"][::std::mem::align_of::<YR_AC_MATCH>() - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RE_NODE {
    pub type_: ::std::os::raw::c_int,
    pub __bindgen_anon_1: RE_NODE__bindgen_ty_1,
    pub __bindgen_anon_2: RE_NODE__bindgen_ty_2,
    pub greedy: ::std::os::raw::c_int,
    pub re_class: *mut RE_CLASS,
    pub children_head: *mut RE_NODE,
    pub children_tail: *mut RE_NODE,
    pub prev_sibling: *mut RE_NODE,
    pub next_sibling: *mut RE_NODE,
    pub forward_code_ref: YR_ARENA_REF,
    pub backward_code_ref: YR_ARENA_REF,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union RE_NODE__bindgen_ty_1 {
    pub value: ::std::os::raw::c_int,
    pub count: ::std::os::raw::c_int,
    pub start: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_NODE__bindgen_ty_1"][::std::mem::size_of::<RE_NODE__bindgen_ty_1>() - 4usize];
    ["Alignment of RE_NODE__bindgen_ty_1"]
        [::std::mem::align_of::<RE_NODE__bindgen_ty_1>() - 4usize];
    ["Offset of field: RE_NODE__bindgen_ty_1::value"]
        [::std::mem::offset_of!(RE_NODE__bindgen_ty_1, value) - 0usize];
    ["Offset of field: RE_NODE__bindgen_ty_1::count"]
        [::std::mem::offset_of!(RE_NODE__bindgen_ty_1, count) - 0usize];
    ["Offset of field: RE_NODE__bindgen_ty_1::start"]
        [::std::mem::offset_of!(RE_NODE__bindgen_ty_1, start) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union RE_NODE__bindgen_ty_2 {
    pub mask: ::std::os::raw::c_int,
    pub end: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_NODE__bindgen_ty_2"][::std::mem::size_of::<RE_NODE__bindgen_ty_2>() - 4usize];
    ["Alignment of RE_NODE__bindgen_ty_2"]
        [::std::mem::align_of::<RE_NODE__bindgen_ty_2>() - 4usize];
    ["Offset of field: RE_NODE__bindgen_ty_2::mask"]
        [::std::mem::offset_of!(RE_NODE__bindgen_ty_2, mask) - 0usize];
    ["Offset of field: RE_NODE__bindgen_ty_2::end"]
        [::std::mem::offset_of!(RE_NODE__bindgen_ty_2, end) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_NODE"][::std::mem::size_of::<RE_NODE>() - 72usize];
    ["Alignment of RE_NODE"][::std::mem::align_of::<RE_NODE>() - 8usize];
    ["Offset of field: RE_NODE::type_"][::std::mem::offset_of!(RE_NODE, type_) - 0usize];
    ["Offset of field: RE_NODE::greedy"][::std::mem::offset_of!(RE_NODE, greedy) - 12usize];
    ["Offset of field: RE_NODE::re_class"][::std::mem::offset_of!(RE_NODE, re_class) - 16usize];
    ["Offset of field: RE_NODE::children_head"]
        [::std::mem::offset_of!(RE_NODE, children_head) - 24usize];
    ["Offset of field: RE_NODE::children_tail"]
        [::std::mem::offset_of!(RE_NODE, children_tail) - 32usize];
    ["Offset of field: RE_NODE::prev_sibling"]
        [::std::mem::offset_of!(RE_NODE, prev_sibling) - 40usize];
    ["Offset of field: RE_NODE::next_sibling"]
        [::std::mem::offset_of!(RE_NODE, next_sibling) - 48usize];
    ["Offset of field: RE_NODE::forward_code_ref"]
        [::std::mem::offset_of!(RE_NODE, forward_code_ref) - 56usize];
    ["Offset of field: RE_NODE::backward_code_ref"]
        [::std::mem::offset_of!(RE_NODE, backward_code_ref) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_CLASS {
    pub negated: u8,
    pub bitmap: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_CLASS"][::std::mem::size_of::<RE_CLASS>() - 33usize];
    ["Alignment of RE_CLASS"][::std::mem::align_of::<RE_CLASS>() - 1usize];
    ["Offset of field: RE_CLASS::negated"][::std::mem::offset_of!(RE_CLASS, negated) - 0usize];
    ["Offset of field: RE_CLASS::bitmap"][::std::mem::offset_of!(RE_CLASS, bitmap) - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_AST {
    pub flags: u32,
    pub root_node: *mut RE_NODE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_AST"][::std::mem::size_of::<RE_AST>() - 16usize];
    ["Alignment of RE_AST"][::std::mem::align_of::<RE_AST>() - 8usize];
    ["Offset of field: RE_AST::flags"][::std::mem::offset_of!(RE_AST, flags) - 0usize];
    ["Offset of field: RE_AST::root_node"][::std::mem::offset_of!(RE_AST, root_node) - 8usize];
};
#[repr(C, packed)]
pub struct RE {
    pub flags: u32,
    pub code: __IncompleteArrayField<u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE"][::std::mem::size_of::<RE>() - 4usize];
    ["Alignment of RE"][::std::mem::align_of::<RE>() - 1usize];
    ["Offset of field: RE::flags"][::std::mem::offset_of!(RE, flags) - 0usize];
    ["Offset of field: RE::code"][::std::mem::offset_of!(RE, code) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_FIBER {
    pub ip: *const u8,
    pub sp: i32,
    pub rc: i32,
    pub prev: *mut RE_FIBER,
    pub next: *mut RE_FIBER,
    pub stack: [u16; 1024usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_FIBER"][::std::mem::size_of::<RE_FIBER>() - 2080usize];
    ["Alignment of RE_FIBER"][::std::mem::align_of::<RE_FIBER>() - 8usize];
    ["Offset of field: RE_FIBER::ip"][::std::mem::offset_of!(RE_FIBER, ip) - 0usize];
    ["Offset of field: RE_FIBER::sp"][::std::mem::offset_of!(RE_FIBER, sp) - 8usize];
    ["Offset of field: RE_FIBER::rc"][::std::mem::offset_of!(RE_FIBER, rc) - 12usize];
    ["Offset of field: RE_FIBER::prev"][::std::mem::offset_of!(RE_FIBER, prev) - 16usize];
    ["Offset of field: RE_FIBER::next"][::std::mem::offset_of!(RE_FIBER, next) - 24usize];
    ["Offset of field: RE_FIBER::stack"][::std::mem::offset_of!(RE_FIBER, stack) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_FIBER_LIST {
    pub head: *mut RE_FIBER,
    pub tail: *mut RE_FIBER,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_FIBER_LIST"][::std::mem::size_of::<RE_FIBER_LIST>() - 16usize];
    ["Alignment of RE_FIBER_LIST"][::std::mem::align_of::<RE_FIBER_LIST>() - 8usize];
    ["Offset of field: RE_FIBER_LIST::head"][::std::mem::offset_of!(RE_FIBER_LIST, head) - 0usize];
    ["Offset of field: RE_FIBER_LIST::tail"][::std::mem::offset_of!(RE_FIBER_LIST, tail) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_FIBER_POOL {
    pub fiber_count: ::std::os::raw::c_int,
    pub fibers: RE_FIBER_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_FIBER_POOL"][::std::mem::size_of::<RE_FIBER_POOL>() - 24usize];
    ["Alignment of RE_FIBER_POOL"][::std::mem::align_of::<RE_FIBER_POOL>() - 8usize];
    ["Offset of field: RE_FIBER_POOL::fiber_count"]
        [::std::mem::offset_of!(RE_FIBER_POOL, fiber_count) - 0usize];
    ["Offset of field: RE_FIBER_POOL::fibers"]
        [::std::mem::offset_of!(RE_FIBER_POOL, fibers) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_FAST_EXEC_POSITION {
    pub round: ::std::os::raw::c_int,
    pub input: *const u8,
    pub prev: *mut RE_FAST_EXEC_POSITION,
    pub next: *mut RE_FAST_EXEC_POSITION,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_FAST_EXEC_POSITION"][::std::mem::size_of::<RE_FAST_EXEC_POSITION>() - 32usize];
    ["Alignment of RE_FAST_EXEC_POSITION"]
        [::std::mem::align_of::<RE_FAST_EXEC_POSITION>() - 8usize];
    ["Offset of field: RE_FAST_EXEC_POSITION::round"]
        [::std::mem::offset_of!(RE_FAST_EXEC_POSITION, round) - 0usize];
    ["Offset of field: RE_FAST_EXEC_POSITION::input"]
        [::std::mem::offset_of!(RE_FAST_EXEC_POSITION, input) - 8usize];
    ["Offset of field: RE_FAST_EXEC_POSITION::prev"]
        [::std::mem::offset_of!(RE_FAST_EXEC_POSITION, prev) - 16usize];
    ["Offset of field: RE_FAST_EXEC_POSITION::next"]
        [::std::mem::offset_of!(RE_FAST_EXEC_POSITION, next) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RE_FAST_EXEC_POSITION_POOL {
    pub head: *mut RE_FAST_EXEC_POSITION,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RE_FAST_EXEC_POSITION_POOL"]
        [::std::mem::size_of::<RE_FAST_EXEC_POSITION_POOL>() - 8usize];
    ["Alignment of RE_FAST_EXEC_POSITION_POOL"]
        [::std::mem::align_of::<RE_FAST_EXEC_POSITION_POOL>() - 8usize];
    ["Offset of field: RE_FAST_EXEC_POSITION_POOL::head"]
        [::std::mem::offset_of!(RE_FAST_EXEC_POSITION_POOL, head) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_MATCHES {
    pub head: *mut YR_MATCH,
    pub tail: *mut YR_MATCH,
    pub count: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_MATCHES"][::std::mem::size_of::<YR_MATCHES>() - 24usize];
    ["Alignment of YR_MATCHES"][::std::mem::align_of::<YR_MATCHES>() - 8usize];
    ["Offset of field: YR_MATCHES::head"][::std::mem::offset_of!(YR_MATCHES, head) - 0usize];
    ["Offset of field: YR_MATCHES::tail"][::std::mem::offset_of!(YR_MATCHES, tail) - 8usize];
    ["Offset of field: YR_MATCHES::count"][::std::mem::offset_of!(YR_MATCHES, count) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_MATCH {
    pub base: i64,
    pub offset: i64,
    pub match_length: i32,
    pub data_length: i32,
    pub data: *const u8,
    pub prev: *mut YR_MATCH,
    pub next: *mut YR_MATCH,
    pub chain_length: i32,
    pub is_private: bool,
    pub xor_key: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_MATCH"][::std::mem::size_of::<YR_MATCH>() - 56usize];
    ["Alignment of YR_MATCH"][::std::mem::align_of::<YR_MATCH>() - 8usize];
    ["Offset of field: YR_MATCH::base"][::std::mem::offset_of!(YR_MATCH, base) - 0usize];
    ["Offset of field: YR_MATCH::offset"][::std::mem::offset_of!(YR_MATCH, offset) - 8usize];
    ["Offset of field: YR_MATCH::match_length"]
        [::std::mem::offset_of!(YR_MATCH, match_length) - 16usize];
    ["Offset of field: YR_MATCH::data_length"]
        [::std::mem::offset_of!(YR_MATCH, data_length) - 20usize];
    ["Offset of field: YR_MATCH::data"][::std::mem::offset_of!(YR_MATCH, data) - 24usize];
    ["Offset of field: YR_MATCH::prev"][::std::mem::offset_of!(YR_MATCH, prev) - 32usize];
    ["Offset of field: YR_MATCH::next"][::std::mem::offset_of!(YR_MATCH, next) - 40usize];
    ["Offset of field: YR_MATCH::chain_length"]
        [::std::mem::offset_of!(YR_MATCH, chain_length) - 48usize];
    ["Offset of field: YR_MATCH::is_private"]
        [::std::mem::offset_of!(YR_MATCH, is_private) - 52usize];
    ["Offset of field: YR_MATCH::xor_key"][::std::mem::offset_of!(YR_MATCH, xor_key) - 53usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct YR_AC_AUTOMATON {
    pub _bindgen_opaque_blob: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_AC_AUTOMATON"][::std::mem::size_of::<YR_AC_AUTOMATON>() - 32usize];
    ["Alignment of YR_AC_AUTOMATON"][::std::mem::align_of::<YR_AC_AUTOMATON>() - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_RULES {
    pub arena: *mut YR_ARENA,
    pub __bindgen_anon_1: YR_RULES__bindgen_ty_1,
    pub __bindgen_anon_2: YR_RULES__bindgen_ty_2,
    pub __bindgen_anon_3: YR_RULES__bindgen_ty_3,
    pub ac_transition_table: *mut YR_AC_TRANSITION,
    pub ac_match_pool: *mut YR_AC_MATCH,
    pub ac_match_table: *mut u32,
    pub code_start: *const u8,
    pub no_required_strings: *mut ::std::os::raw::c_ulong,
    pub num_rules: u32,
    pub num_strings: u32,
    pub num_namespaces: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULES__bindgen_ty_1 {
    pub rules_table: *mut YR_RULE,
    pub rules_list_head: *mut YR_RULE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULES__bindgen_ty_1"][::std::mem::size_of::<YR_RULES__bindgen_ty_1>() - 8usize];
    ["Alignment of YR_RULES__bindgen_ty_1"]
        [::std::mem::align_of::<YR_RULES__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_RULES__bindgen_ty_1::rules_table"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_1, rules_table) - 0usize];
    ["Offset of field: YR_RULES__bindgen_ty_1::rules_list_head"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_1, rules_list_head) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULES__bindgen_ty_2 {
    pub strings_table: *mut YR_STRING,
    pub strings_list_head: *mut YR_STRING,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULES__bindgen_ty_2"][::std::mem::size_of::<YR_RULES__bindgen_ty_2>() - 8usize];
    ["Alignment of YR_RULES__bindgen_ty_2"]
        [::std::mem::align_of::<YR_RULES__bindgen_ty_2>() - 8usize];
    ["Offset of field: YR_RULES__bindgen_ty_2::strings_table"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_2, strings_table) - 0usize];
    ["Offset of field: YR_RULES__bindgen_ty_2::strings_list_head"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_2, strings_list_head) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_RULES__bindgen_ty_3 {
    pub ext_vars_table: *mut YR_EXTERNAL_VARIABLE,
    pub externals_list_head: *mut YR_EXTERNAL_VARIABLE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULES__bindgen_ty_3"][::std::mem::size_of::<YR_RULES__bindgen_ty_3>() - 8usize];
    ["Alignment of YR_RULES__bindgen_ty_3"]
        [::std::mem::align_of::<YR_RULES__bindgen_ty_3>() - 8usize];
    ["Offset of field: YR_RULES__bindgen_ty_3::ext_vars_table"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_3, ext_vars_table) - 0usize];
    ["Offset of field: YR_RULES__bindgen_ty_3::externals_list_head"]
        [::std::mem::offset_of!(YR_RULES__bindgen_ty_3, externals_list_head) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULES"][::std::mem::size_of::<YR_RULES>() - 88usize];
    ["Alignment of YR_RULES"][::std::mem::align_of::<YR_RULES>() - 8usize];
    ["Offset of field: YR_RULES::arena"][::std::mem::offset_of!(YR_RULES, arena) - 0usize];
    ["Offset of field: YR_RULES::ac_transition_table"]
        [::std::mem::offset_of!(YR_RULES, ac_transition_table) - 32usize];
    ["Offset of field: YR_RULES::ac_match_pool"]
        [::std::mem::offset_of!(YR_RULES, ac_match_pool) - 40usize];
    ["Offset of field: YR_RULES::ac_match_table"]
        [::std::mem::offset_of!(YR_RULES, ac_match_table) - 48usize];
    ["Offset of field: YR_RULES::code_start"]
        [::std::mem::offset_of!(YR_RULES, code_start) - 56usize];
    ["Offset of field: YR_RULES::no_required_strings"]
        [::std::mem::offset_of!(YR_RULES, no_required_strings) - 64usize];
    ["Offset of field: YR_RULES::num_rules"][::std::mem::offset_of!(YR_RULES, num_rules) - 72usize];
    ["Offset of field: YR_RULES::num_strings"]
        [::std::mem::offset_of!(YR_RULES, num_strings) - 76usize];
    ["Offset of field: YR_RULES::num_namespaces"]
        [::std::mem::offset_of!(YR_RULES, num_namespaces) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_RULES_STATS {
    pub num_rules: u32,
    pub num_strings: u32,
    pub ac_matches: u32,
    pub ac_root_match_list_length: u32,
    pub ac_average_match_list_length: f32,
    pub top_ac_match_list_lengths: [u32; 100usize],
    pub ac_match_list_length_pctls: [u32; 101usize],
    pub ac_tables_size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULES_STATS"][::std::mem::size_of::<YR_RULES_STATS>() - 828usize];
    ["Alignment of YR_RULES_STATS"][::std::mem::align_of::<YR_RULES_STATS>() - 4usize];
    ["Offset of field: YR_RULES_STATS::num_rules"]
        [::std::mem::offset_of!(YR_RULES_STATS, num_rules) - 0usize];
    ["Offset of field: YR_RULES_STATS::num_strings"]
        [::std::mem::offset_of!(YR_RULES_STATS, num_strings) - 4usize];
    ["Offset of field: YR_RULES_STATS::ac_matches"]
        [::std::mem::offset_of!(YR_RULES_STATS, ac_matches) - 8usize];
    ["Offset of field: YR_RULES_STATS::ac_root_match_list_length"]
        [::std::mem::offset_of!(YR_RULES_STATS, ac_root_match_list_length) - 12usize];
    ["Offset of field: YR_RULES_STATS::ac_average_match_list_length"]
        [::std::mem::offset_of!(YR_RULES_STATS, ac_average_match_list_length) - 16usize];
    ["Offset of field: YR_RULES_STATS::top_ac_match_list_lengths"]
        [::std::mem::offset_of!(YR_RULES_STATS, top_ac_match_list_lengths) - 20usize];
    ["Offset of field: YR_RULES_STATS::ac_match_list_length_pctls"]
        [::std::mem::offset_of!(YR_RULES_STATS, ac_match_list_length_pctls) - 420usize];
    ["Offset of field: YR_RULES_STATS::ac_tables_size"]
        [::std::mem::offset_of!(YR_RULES_STATS, ac_tables_size) - 824usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_PROFILING_INFO {
    pub atom_matches: u32,
    pub match_time: u64,
    pub exec_time: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_PROFILING_INFO"][::std::mem::size_of::<YR_PROFILING_INFO>() - 24usize];
    ["Alignment of YR_PROFILING_INFO"][::std::mem::align_of::<YR_PROFILING_INFO>() - 8usize];
    ["Offset of field: YR_PROFILING_INFO::atom_matches"]
        [::std::mem::offset_of!(YR_PROFILING_INFO, atom_matches) - 0usize];
    ["Offset of field: YR_PROFILING_INFO::match_time"]
        [::std::mem::offset_of!(YR_PROFILING_INFO, match_time) - 8usize];
    ["Offset of field: YR_PROFILING_INFO::exec_time"]
        [::std::mem::offset_of!(YR_PROFILING_INFO, exec_time) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_RULE_PROFILING_INFO {
    pub rule: *mut YR_RULE,
    pub cost: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_RULE_PROFILING_INFO"][::std::mem::size_of::<YR_RULE_PROFILING_INFO>() - 16usize];
    ["Alignment of YR_RULE_PROFILING_INFO"]
        [::std::mem::align_of::<YR_RULE_PROFILING_INFO>() - 8usize];
    ["Offset of field: YR_RULE_PROFILING_INFO::rule"]
        [::std::mem::offset_of!(YR_RULE_PROFILING_INFO, rule) - 0usize];
    ["Offset of field: YR_RULE_PROFILING_INFO::cost"]
        [::std::mem::offset_of!(YR_RULE_PROFILING_INFO, cost) - 8usize];
};
pub type YR_MEMORY_BLOCK_FETCH_DATA_FUNC =
    ::std::option::Option<unsafe extern "C" fn(self_: *mut YR_MEMORY_BLOCK) -> *const u8>;
pub type YR_MEMORY_BLOCK_ITERATOR_FUNC = ::std::option::Option<
    unsafe extern "C" fn(self_: *mut YR_MEMORY_BLOCK_ITERATOR) -> *mut YR_MEMORY_BLOCK,
>;
pub type YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC =
    ::std::option::Option<unsafe extern "C" fn(self_: *mut YR_MEMORY_BLOCK_ITERATOR) -> u64>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_MEMORY_BLOCK {
    pub size: size_t,
    pub base: u64,
    pub context: *mut ::std::os::raw::c_void,
    pub fetch_data: YR_MEMORY_BLOCK_FETCH_DATA_FUNC,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_MEMORY_BLOCK"][::std::mem::size_of::<YR_MEMORY_BLOCK>() - 32usize];
    ["Alignment of YR_MEMORY_BLOCK"][::std::mem::align_of::<YR_MEMORY_BLOCK>() - 8usize];
    ["Offset of field: YR_MEMORY_BLOCK::size"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK, size) - 0usize];
    ["Offset of field: YR_MEMORY_BLOCK::base"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK, base) - 8usize];
    ["Offset of field: YR_MEMORY_BLOCK::context"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK, context) - 16usize];
    ["Offset of field: YR_MEMORY_BLOCK::fetch_data"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK, fetch_data) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_MEMORY_BLOCK_ITERATOR {
    pub context: *mut ::std::os::raw::c_void,
    pub first: YR_MEMORY_BLOCK_ITERATOR_FUNC,
    pub next: YR_MEMORY_BLOCK_ITERATOR_FUNC,
    pub file_size: YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC,
    pub last_error: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_MEMORY_BLOCK_ITERATOR"]
        [::std::mem::size_of::<YR_MEMORY_BLOCK_ITERATOR>() - 40usize];
    ["Alignment of YR_MEMORY_BLOCK_ITERATOR"]
        [::std::mem::align_of::<YR_MEMORY_BLOCK_ITERATOR>() - 8usize];
    ["Offset of field: YR_MEMORY_BLOCK_ITERATOR::context"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK_ITERATOR, context) - 0usize];
    ["Offset of field: YR_MEMORY_BLOCK_ITERATOR::first"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK_ITERATOR, first) - 8usize];
    ["Offset of field: YR_MEMORY_BLOCK_ITERATOR::next"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK_ITERATOR, next) - 16usize];
    ["Offset of field: YR_MEMORY_BLOCK_ITERATOR::file_size"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK_ITERATOR, file_size) - 24usize];
    ["Offset of field: YR_MEMORY_BLOCK_ITERATOR::last_error"]
        [::std::mem::offset_of!(YR_MEMORY_BLOCK_ITERATOR, last_error) - 32usize];
};
pub type YR_CALLBACK_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut YR_SCAN_CONTEXT,
        message: ::std::os::raw::c_int,
        message_data: *mut ::std::os::raw::c_void,
        user_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_SCAN_CONTEXT {
    pub file_size: u64,
    pub entry_point: u64,
    pub flags: ::std::os::raw::c_int,
    pub canary: ::std::os::raw::c_int,
    pub timeout: u64,
    pub user_data: *mut ::std::os::raw::c_void,
    pub callback: YR_CALLBACK_FUNC,
    pub rules: *mut YR_RULES,
    pub last_error_string: *mut YR_STRING,
    pub iterator: *mut YR_MEMORY_BLOCK_ITERATOR,
    pub objects_table: *mut YR_HASH_TABLE,
    pub matches_notebook: *mut YR_NOTEBOOK,
    pub stopwatch: YR_STOPWATCH,
    pub re_fiber_pool: RE_FIBER_POOL,
    pub re_fast_exec_position_pool: RE_FAST_EXEC_POSITION_POOL,
    pub rule_matches_flags: *mut ::std::os::raw::c_ulong,
    pub ns_unsatisfied_flags: *mut ::std::os::raw::c_ulong,
    pub strings_temp_disabled: *mut ::std::os::raw::c_ulong,
    pub matches: *mut YR_MATCHES,
    pub unconfirmed_matches: *mut YR_MATCHES,
    pub required_eval: *mut ::std::os::raw::c_ulong,
    pub profiling_info: *mut YR_PROFILING_INFO,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_SCAN_CONTEXT"][::std::mem::size_of::<YR_SCAN_CONTEXT>() - 192usize];
    ["Alignment of YR_SCAN_CONTEXT"][::std::mem::align_of::<YR_SCAN_CONTEXT>() - 8usize];
    ["Offset of field: YR_SCAN_CONTEXT::file_size"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, file_size) - 0usize];
    ["Offset of field: YR_SCAN_CONTEXT::entry_point"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, entry_point) - 8usize];
    ["Offset of field: YR_SCAN_CONTEXT::flags"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, flags) - 16usize];
    ["Offset of field: YR_SCAN_CONTEXT::canary"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, canary) - 20usize];
    ["Offset of field: YR_SCAN_CONTEXT::timeout"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, timeout) - 24usize];
    ["Offset of field: YR_SCAN_CONTEXT::user_data"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, user_data) - 32usize];
    ["Offset of field: YR_SCAN_CONTEXT::callback"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, callback) - 40usize];
    ["Offset of field: YR_SCAN_CONTEXT::rules"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, rules) - 48usize];
    ["Offset of field: YR_SCAN_CONTEXT::last_error_string"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, last_error_string) - 56usize];
    ["Offset of field: YR_SCAN_CONTEXT::iterator"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, iterator) - 64usize];
    ["Offset of field: YR_SCAN_CONTEXT::objects_table"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, objects_table) - 72usize];
    ["Offset of field: YR_SCAN_CONTEXT::matches_notebook"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, matches_notebook) - 80usize];
    ["Offset of field: YR_SCAN_CONTEXT::stopwatch"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, stopwatch) - 88usize];
    ["Offset of field: YR_SCAN_CONTEXT::re_fiber_pool"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, re_fiber_pool) - 104usize];
    ["Offset of field: YR_SCAN_CONTEXT::re_fast_exec_position_pool"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, re_fast_exec_position_pool) - 128usize];
    ["Offset of field: YR_SCAN_CONTEXT::rule_matches_flags"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, rule_matches_flags) - 136usize];
    ["Offset of field: YR_SCAN_CONTEXT::ns_unsatisfied_flags"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, ns_unsatisfied_flags) - 144usize];
    ["Offset of field: YR_SCAN_CONTEXT::strings_temp_disabled"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, strings_temp_disabled) - 152usize];
    ["Offset of field: YR_SCAN_CONTEXT::matches"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, matches) - 160usize];
    ["Offset of field: YR_SCAN_CONTEXT::unconfirmed_matches"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, unconfirmed_matches) - 168usize];
    ["Offset of field: YR_SCAN_CONTEXT::required_eval"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, required_eval) - 176usize];
    ["Offset of field: YR_SCAN_CONTEXT::profiling_info"]
        [::std::mem::offset_of!(YR_SCAN_CONTEXT, profiling_info) - 184usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_VALUE {
    pub i: i64,
    pub d: f64,
    pub p: *mut ::std::os::raw::c_void,
    pub o: *mut YR_OBJECT,
    pub s: *mut YR_STRING,
    pub it: *mut YR_ITERATOR,
    pub ss: *mut SIZED_STRING,
    pub re: *mut RE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_VALUE"][::std::mem::size_of::<YR_VALUE>() - 8usize];
    ["Alignment of YR_VALUE"][::std::mem::align_of::<YR_VALUE>() - 8usize];
    ["Offset of field: YR_VALUE::i"][::std::mem::offset_of!(YR_VALUE, i) - 0usize];
    ["Offset of field: YR_VALUE::d"][::std::mem::offset_of!(YR_VALUE, d) - 0usize];
    ["Offset of field: YR_VALUE::p"][::std::mem::offset_of!(YR_VALUE, p) - 0usize];
    ["Offset of field: YR_VALUE::o"][::std::mem::offset_of!(YR_VALUE, o) - 0usize];
    ["Offset of field: YR_VALUE::s"][::std::mem::offset_of!(YR_VALUE, s) - 0usize];
    ["Offset of field: YR_VALUE::it"][::std::mem::offset_of!(YR_VALUE, it) - 0usize];
    ["Offset of field: YR_VALUE::ss"][::std::mem::offset_of!(YR_VALUE, ss) - 0usize];
    ["Offset of field: YR_VALUE::re"][::std::mem::offset_of!(YR_VALUE, re) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_OBJECT {
    pub canary: ::std::os::raw::c_int,
    pub type_: i8,
    pub identifier: *const ::std::os::raw::c_char,
    pub parent: *mut YR_OBJECT,
    pub data: *mut ::std::os::raw::c_void,
    pub value: YR_VALUE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_OBJECT"][::std::mem::size_of::<YR_OBJECT>() - 40usize];
    ["Alignment of YR_OBJECT"][::std::mem::align_of::<YR_OBJECT>() - 8usize];
    ["Offset of field: YR_OBJECT::canary"][::std::mem::offset_of!(YR_OBJECT, canary) - 0usize];
    ["Offset of field: YR_OBJECT::type_"][::std::mem::offset_of!(YR_OBJECT, type_) - 4usize];
    ["Offset of field: YR_OBJECT::identifier"]
        [::std::mem::offset_of!(YR_OBJECT, identifier) - 8usize];
    ["Offset of field: YR_OBJECT::parent"][::std::mem::offset_of!(YR_OBJECT, parent) - 16usize];
    ["Offset of field: YR_OBJECT::data"][::std::mem::offset_of!(YR_OBJECT, data) - 24usize];
    ["Offset of field: YR_OBJECT::value"][::std::mem::offset_of!(YR_OBJECT, value) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_OBJECT_STRUCTURE {
    pub canary: ::std::os::raw::c_int,
    pub type_: i8,
    pub identifier: *const ::std::os::raw::c_char,
    pub parent: *mut YR_OBJECT,
    pub data: *mut ::std::os::raw::c_void,
    pub members: *mut YR_STRUCTURE_MEMBER,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_OBJECT_STRUCTURE"][::std::mem::size_of::<YR_OBJECT_STRUCTURE>() - 40usize];
    ["Alignment of YR_OBJECT_STRUCTURE"][::std::mem::align_of::<YR_OBJECT_STRUCTURE>() - 8usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::canary"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, canary) - 0usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::type_"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, type_) - 4usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::identifier"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, identifier) - 8usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::parent"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, parent) - 16usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::data"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, data) - 24usize];
    ["Offset of field: YR_OBJECT_STRUCTURE::members"]
        [::std::mem::offset_of!(YR_OBJECT_STRUCTURE, members) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_OBJECT_ARRAY {
    pub canary: ::std::os::raw::c_int,
    pub type_: i8,
    pub identifier: *const ::std::os::raw::c_char,
    pub parent: *mut YR_OBJECT,
    pub data: *mut ::std::os::raw::c_void,
    pub prototype_item: *mut YR_OBJECT,
    pub items: *mut YR_ARRAY_ITEMS,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_OBJECT_ARRAY"][::std::mem::size_of::<YR_OBJECT_ARRAY>() - 48usize];
    ["Alignment of YR_OBJECT_ARRAY"][::std::mem::align_of::<YR_OBJECT_ARRAY>() - 8usize];
    ["Offset of field: YR_OBJECT_ARRAY::canary"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, canary) - 0usize];
    ["Offset of field: YR_OBJECT_ARRAY::type_"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, type_) - 4usize];
    ["Offset of field: YR_OBJECT_ARRAY::identifier"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, identifier) - 8usize];
    ["Offset of field: YR_OBJECT_ARRAY::parent"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, parent) - 16usize];
    ["Offset of field: YR_OBJECT_ARRAY::data"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, data) - 24usize];
    ["Offset of field: YR_OBJECT_ARRAY::prototype_item"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, prototype_item) - 32usize];
    ["Offset of field: YR_OBJECT_ARRAY::items"]
        [::std::mem::offset_of!(YR_OBJECT_ARRAY, items) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_OBJECT_DICTIONARY {
    pub canary: ::std::os::raw::c_int,
    pub type_: i8,
    pub identifier: *const ::std::os::raw::c_char,
    pub parent: *mut YR_OBJECT,
    pub data: *mut ::std::os::raw::c_void,
    pub prototype_item: *mut YR_OBJECT,
    pub items: *mut YR_DICTIONARY_ITEMS,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_OBJECT_DICTIONARY"][::std::mem::size_of::<YR_OBJECT_DICTIONARY>() - 48usize];
    ["Alignment of YR_OBJECT_DICTIONARY"][::std::mem::align_of::<YR_OBJECT_DICTIONARY>() - 8usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::canary"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, canary) - 0usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::type_"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, type_) - 4usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::identifier"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, identifier) - 8usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::parent"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, parent) - 16usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::data"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, data) - 24usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::prototype_item"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, prototype_item) - 32usize];
    ["Offset of field: YR_OBJECT_DICTIONARY::items"]
        [::std::mem::offset_of!(YR_OBJECT_DICTIONARY, items) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_STRUCTURE_MEMBER {
    pub object: *mut YR_OBJECT,
    pub next: *mut YR_STRUCTURE_MEMBER,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRUCTURE_MEMBER"][::std::mem::size_of::<YR_STRUCTURE_MEMBER>() - 16usize];
    ["Alignment of YR_STRUCTURE_MEMBER"][::std::mem::align_of::<YR_STRUCTURE_MEMBER>() - 8usize];
    ["Offset of field: YR_STRUCTURE_MEMBER::object"]
        [::std::mem::offset_of!(YR_STRUCTURE_MEMBER, object) - 0usize];
    ["Offset of field: YR_STRUCTURE_MEMBER::next"]
        [::std::mem::offset_of!(YR_STRUCTURE_MEMBER, next) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_ARRAY_ITEMS {
    pub capacity: ::std::os::raw::c_int,
    pub length: ::std::os::raw::c_int,
    pub objects: [*mut YR_OBJECT; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ARRAY_ITEMS"][::std::mem::size_of::<YR_ARRAY_ITEMS>() - 16usize];
    ["Alignment of YR_ARRAY_ITEMS"][::std::mem::align_of::<YR_ARRAY_ITEMS>() - 8usize];
    ["Offset of field: YR_ARRAY_ITEMS::capacity"]
        [::std::mem::offset_of!(YR_ARRAY_ITEMS, capacity) - 0usize];
    ["Offset of field: YR_ARRAY_ITEMS::length"]
        [::std::mem::offset_of!(YR_ARRAY_ITEMS, length) - 4usize];
    ["Offset of field: YR_ARRAY_ITEMS::objects"]
        [::std::mem::offset_of!(YR_ARRAY_ITEMS, objects) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_DICTIONARY_ITEMS {
    pub used: ::std::os::raw::c_int,
    pub free: ::std::os::raw::c_int,
    pub objects: [YR_DICTIONARY_ITEMS__bindgen_ty_1; 1usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_DICTIONARY_ITEMS__bindgen_ty_1 {
    pub key: *mut SIZED_STRING,
    pub obj: *mut YR_OBJECT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_DICTIONARY_ITEMS__bindgen_ty_1"]
        [::std::mem::size_of::<YR_DICTIONARY_ITEMS__bindgen_ty_1>() - 16usize];
    ["Alignment of YR_DICTIONARY_ITEMS__bindgen_ty_1"]
        [::std::mem::align_of::<YR_DICTIONARY_ITEMS__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_DICTIONARY_ITEMS__bindgen_ty_1::key"]
        [::std::mem::offset_of!(YR_DICTIONARY_ITEMS__bindgen_ty_1, key) - 0usize];
    ["Offset of field: YR_DICTIONARY_ITEMS__bindgen_ty_1::obj"]
        [::std::mem::offset_of!(YR_DICTIONARY_ITEMS__bindgen_ty_1, obj) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_DICTIONARY_ITEMS"][::std::mem::size_of::<YR_DICTIONARY_ITEMS>() - 24usize];
    ["Alignment of YR_DICTIONARY_ITEMS"][::std::mem::align_of::<YR_DICTIONARY_ITEMS>() - 8usize];
    ["Offset of field: YR_DICTIONARY_ITEMS::used"]
        [::std::mem::offset_of!(YR_DICTIONARY_ITEMS, used) - 0usize];
    ["Offset of field: YR_DICTIONARY_ITEMS::free"]
        [::std::mem::offset_of!(YR_DICTIONARY_ITEMS, free) - 4usize];
    ["Offset of field: YR_DICTIONARY_ITEMS::objects"]
        [::std::mem::offset_of!(YR_DICTIONARY_ITEMS, objects) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_ARRAY_ITERATOR {
    pub array: *mut YR_OBJECT,
    pub index: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ARRAY_ITERATOR"][::std::mem::size_of::<YR_ARRAY_ITERATOR>() - 16usize];
    ["Alignment of YR_ARRAY_ITERATOR"][::std::mem::align_of::<YR_ARRAY_ITERATOR>() - 8usize];
    ["Offset of field: YR_ARRAY_ITERATOR::array"]
        [::std::mem::offset_of!(YR_ARRAY_ITERATOR, array) - 0usize];
    ["Offset of field: YR_ARRAY_ITERATOR::index"]
        [::std::mem::offset_of!(YR_ARRAY_ITERATOR, index) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_DICT_ITERATOR {
    pub dict: *mut YR_OBJECT,
    pub index: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_DICT_ITERATOR"][::std::mem::size_of::<YR_DICT_ITERATOR>() - 16usize];
    ["Alignment of YR_DICT_ITERATOR"][::std::mem::align_of::<YR_DICT_ITERATOR>() - 8usize];
    ["Offset of field: YR_DICT_ITERATOR::dict"]
        [::std::mem::offset_of!(YR_DICT_ITERATOR, dict) - 0usize];
    ["Offset of field: YR_DICT_ITERATOR::index"]
        [::std::mem::offset_of!(YR_DICT_ITERATOR, index) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_INT_RANGE_ITERATOR {
    pub next: i64,
    pub last: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_INT_RANGE_ITERATOR"][::std::mem::size_of::<YR_INT_RANGE_ITERATOR>() - 16usize];
    ["Alignment of YR_INT_RANGE_ITERATOR"]
        [::std::mem::align_of::<YR_INT_RANGE_ITERATOR>() - 8usize];
    ["Offset of field: YR_INT_RANGE_ITERATOR::next"]
        [::std::mem::offset_of!(YR_INT_RANGE_ITERATOR, next) - 0usize];
    ["Offset of field: YR_INT_RANGE_ITERATOR::last"]
        [::std::mem::offset_of!(YR_INT_RANGE_ITERATOR, last) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_INT_ENUM_ITERATOR {
    pub next: i64,
    pub count: i64,
    pub items: [i64; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_INT_ENUM_ITERATOR"][::std::mem::size_of::<YR_INT_ENUM_ITERATOR>() - 24usize];
    ["Alignment of YR_INT_ENUM_ITERATOR"][::std::mem::align_of::<YR_INT_ENUM_ITERATOR>() - 8usize];
    ["Offset of field: YR_INT_ENUM_ITERATOR::next"]
        [::std::mem::offset_of!(YR_INT_ENUM_ITERATOR, next) - 0usize];
    ["Offset of field: YR_INT_ENUM_ITERATOR::count"]
        [::std::mem::offset_of!(YR_INT_ENUM_ITERATOR, count) - 8usize];
    ["Offset of field: YR_INT_ENUM_ITERATOR::items"]
        [::std::mem::offset_of!(YR_INT_ENUM_ITERATOR, items) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_STRING_SET_ITERATOR {
    pub count: i64,
    pub index: i64,
    pub strings: [*mut YR_STRING; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_STRING_SET_ITERATOR"][::std::mem::size_of::<YR_STRING_SET_ITERATOR>() - 24usize];
    ["Alignment of YR_STRING_SET_ITERATOR"]
        [::std::mem::align_of::<YR_STRING_SET_ITERATOR>() - 8usize];
    ["Offset of field: YR_STRING_SET_ITERATOR::count"]
        [::std::mem::offset_of!(YR_STRING_SET_ITERATOR, count) - 0usize];
    ["Offset of field: YR_STRING_SET_ITERATOR::index"]
        [::std::mem::offset_of!(YR_STRING_SET_ITERATOR, index) - 8usize];
    ["Offset of field: YR_STRING_SET_ITERATOR::strings"]
        [::std::mem::offset_of!(YR_STRING_SET_ITERATOR, strings) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_TEXT_STRING_SET_ITERATOR {
    pub count: i64,
    pub index: i64,
    pub strings: [*mut SIZED_STRING; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_TEXT_STRING_SET_ITERATOR"]
        [::std::mem::size_of::<YR_TEXT_STRING_SET_ITERATOR>() - 24usize];
    ["Alignment of YR_TEXT_STRING_SET_ITERATOR"]
        [::std::mem::align_of::<YR_TEXT_STRING_SET_ITERATOR>() - 8usize];
    ["Offset of field: YR_TEXT_STRING_SET_ITERATOR::count"]
        [::std::mem::offset_of!(YR_TEXT_STRING_SET_ITERATOR, count) - 0usize];
    ["Offset of field: YR_TEXT_STRING_SET_ITERATOR::index"]
        [::std::mem::offset_of!(YR_TEXT_STRING_SET_ITERATOR, index) - 8usize];
    ["Offset of field: YR_TEXT_STRING_SET_ITERATOR::strings"]
        [::std::mem::offset_of!(YR_TEXT_STRING_SET_ITERATOR, strings) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct YR_ITERATOR {
    pub next_func_idx: u8,
    pub __bindgen_anon_1: YR_ITERATOR__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union YR_ITERATOR__bindgen_ty_1 {
    pub array_it: YR_ARRAY_ITERATOR,
    pub dict_it: YR_DICT_ITERATOR,
    pub int_range_it: YR_INT_RANGE_ITERATOR,
    pub int_enum_it: YR_INT_ENUM_ITERATOR,
    pub string_set_it: YR_STRING_SET_ITERATOR,
    pub text_string_set_it: YR_TEXT_STRING_SET_ITERATOR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ITERATOR__bindgen_ty_1"]
        [::std::mem::size_of::<YR_ITERATOR__bindgen_ty_1>() - 24usize];
    ["Alignment of YR_ITERATOR__bindgen_ty_1"]
        [::std::mem::align_of::<YR_ITERATOR__bindgen_ty_1>() - 8usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::array_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, array_it) - 0usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::dict_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, dict_it) - 0usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::int_range_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, int_range_it) - 0usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::int_enum_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, int_enum_it) - 0usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::string_set_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, string_set_it) - 0usize];
    ["Offset of field: YR_ITERATOR__bindgen_ty_1::text_string_set_it"]
        [::std::mem::offset_of!(YR_ITERATOR__bindgen_ty_1, text_string_set_it) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ITERATOR"][::std::mem::size_of::<YR_ITERATOR>() - 32usize];
    ["Alignment of YR_ITERATOR"][::std::mem::align_of::<YR_ITERATOR>() - 8usize];
    ["Offset of field: YR_ITERATOR::next_func_idx"]
        [::std::mem::offset_of!(YR_ITERATOR, next_func_idx) - 0usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct YR_ATOMS_CONFIG {
    pub _bindgen_opaque_blob: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_ATOMS_CONFIG"][::std::mem::size_of::<YR_ATOMS_CONFIG>() - 32usize];
    ["Alignment of YR_ATOMS_CONFIG"][::std::mem::align_of::<YR_ATOMS_CONFIG>() - 8usize];
};
pub type YR_COMPILER_CALLBACK_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        error_level: ::std::os::raw::c_int,
        file_name: *const ::std::os::raw::c_char,
        line_number: ::std::os::raw::c_int,
        rule: *const YR_RULE,
        message: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type YR_COMPILER_INCLUDE_CALLBACK_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        include_name: *const ::std::os::raw::c_char,
        calling_rule_filename: *const ::std::os::raw::c_char,
        calling_rule_namespace: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char,
>;
pub type YR_COMPILER_INCLUDE_FREE_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        callback_result_ptr: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type YR_COMPILER_RE_AST_CALLBACK_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        rule: *const YR_RULE,
        string_identifier: *const ::std::os::raw::c_char,
        re_ast: *const RE_AST,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type YR_FIXUP = __BindgenOpaqueArray<u64, 2usize>;
pub type YR_LOOP_CONTEXT = __BindgenOpaqueArray<u64, 13usize>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _YR_COMPILER {
    pub arena: *mut YR_ARENA,
    pub current_rule_idx: u32,
    pub next_rule_idx: u32,
    pub current_string_idx: u32,
    pub current_namespace_idx: u32,
    pub current_meta_idx: u32,
    pub rules: *mut YR_RULES,
    pub errors: ::std::os::raw::c_int,
    pub current_line: ::std::os::raw::c_int,
    pub last_error: ::std::os::raw::c_int,
    pub last_error_line: ::std::os::raw::c_int,
    pub strict_escape: bool,
    pub error_recovery: jmp_buf,
    pub automaton: *mut YR_AC_AUTOMATON,
    pub rules_table: *mut YR_HASH_TABLE,
    pub objects_table: *mut YR_HASH_TABLE,
    pub strings_table: *mut YR_HASH_TABLE,
    pub wildcard_identifiers_table: *mut YR_HASH_TABLE,
    pub sz_table: *mut YR_HASH_TABLE,
    pub fixup_stack_head: *mut YR_FIXUP,
    pub num_namespaces: ::std::os::raw::c_int,
    pub loop_: [YR_LOOP_CONTEXT; 4usize],
    pub loop_index: ::std::os::raw::c_int,
    pub loop_for_of_var_index: ::std::os::raw::c_int,
    pub file_name_stack: [*mut ::std::os::raw::c_char; 16usize],
    pub file_name_stack_ptr: ::std::os::raw::c_int,
    pub last_error_extra_info: [::std::os::raw::c_char; 256usize],
    pub lex_buf: [::std::os::raw::c_char; 8192usize],
    pub lex_buf_ptr: *mut ::std::os::raw::c_char,
    pub lex_buf_len: ::std::os::raw::c_ushort,
    pub include_base_dir: [::std::os::raw::c_char; 4096usize],
    pub user_data: *mut ::std::os::raw::c_void,
    pub incl_clbk_user_data: *mut ::std::os::raw::c_void,
    pub re_ast_clbk_user_data: *mut ::std::os::raw::c_void,
    pub callback: YR_COMPILER_CALLBACK_FUNC,
    pub include_callback: YR_COMPILER_INCLUDE_CALLBACK_FUNC,
    pub include_free: YR_COMPILER_INCLUDE_FREE_FUNC,
    pub re_ast_callback: YR_COMPILER_RE_AST_CALLBACK_FUNC,
    pub atoms_config: YR_ATOMS_CONFIG,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _YR_COMPILER"][::std::mem::size_of::<_YR_COMPILER>() - 13528usize];
    ["Alignment of _YR_COMPILER"][::std::mem::align_of::<_YR_COMPILER>() - 8usize];
    ["Offset of field: _YR_COMPILER::arena"][::std::mem::offset_of!(_YR_COMPILER, arena) - 0usize];
    ["Offset of field: _YR_COMPILER::current_rule_idx"]
        [::std::mem::offset_of!(_YR_COMPILER, current_rule_idx) - 8usize];
    ["Offset of field: _YR_COMPILER::next_rule_idx"]
        [::std::mem::offset_of!(_YR_COMPILER, next_rule_idx) - 12usize];
    ["Offset of field: _YR_COMPILER::current_string_idx"]
        [::std::mem::offset_of!(_YR_COMPILER, current_string_idx) - 16usize];
    ["Offset of field: _YR_COMPILER::current_namespace_idx"]
        [::std::mem::offset_of!(_YR_COMPILER, current_namespace_idx) - 20usize];
    ["Offset of field: _YR_COMPILER::current_meta_idx"]
        [::std::mem::offset_of!(_YR_COMPILER, current_meta_idx) - 24usize];
    ["Offset of field: _YR_COMPILER::rules"][::std::mem::offset_of!(_YR_COMPILER, rules) - 32usize];
    ["Offset of field: _YR_COMPILER::errors"]
        [::std::mem::offset_of!(_YR_COMPILER, errors) - 40usize];
    ["Offset of field: _YR_COMPILER::current_line"]
        [::std::mem::offset_of!(_YR_COMPILER, current_line) - 44usize];
    ["Offset of field: _YR_COMPILER::last_error"]
        [::std::mem::offset_of!(_YR_COMPILER, last_error) - 48usize];
    ["Offset of field: _YR_COMPILER::last_error_line"]
        [::std::mem::offset_of!(_YR_COMPILER, last_error_line) - 52usize];
    ["Offset of field: _YR_COMPILER::strict_escape"]
        [::std::mem::offset_of!(_YR_COMPILER, strict_escape) - 56usize];
    ["Offset of field: _YR_COMPILER::error_recovery"]
        [::std::mem::offset_of!(_YR_COMPILER, error_recovery) - 60usize];
    ["Offset of field: _YR_COMPILER::automaton"]
        [::std::mem::offset_of!(_YR_COMPILER, automaton) - 256usize];
    ["Offset of field: _YR_COMPILER::rules_table"]
        [::std::mem::offset_of!(_YR_COMPILER, rules_table) - 264usize];
    ["Offset of field: _YR_COMPILER::objects_table"]
        [::std::mem::offset_of!(_YR_COMPILER, objects_table) - 272usize];
    ["Offset of field: _YR_COMPILER::strings_table"]
        [::std::mem::offset_of!(_YR_COMPILER, strings_table) - 280usize];
    ["Offset of field: _YR_COMPILER::wildcard_identifiers_table"]
        [::std::mem::offset_of!(_YR_COMPILER, wildcard_identifiers_table) - 288usize];
    ["Offset of field: _YR_COMPILER::sz_table"]
        [::std::mem::offset_of!(_YR_COMPILER, sz_table) - 296usize];
    ["Offset of field: _YR_COMPILER::fixup_stack_head"]
        [::std::mem::offset_of!(_YR_COMPILER, fixup_stack_head) - 304usize];
    ["Offset of field: _YR_COMPILER::num_namespaces"]
        [::std::mem::offset_of!(_YR_COMPILER, num_namespaces) - 312usize];
    ["Offset of field: _YR_COMPILER::loop_"]
        [::std::mem::offset_of!(_YR_COMPILER, loop_) - 320usize];
    ["Offset of field: _YR_COMPILER::loop_index"]
        [::std::mem::offset_of!(_YR_COMPILER, loop_index) - 736usize];
    ["Offset of field: _YR_COMPILER::loop_for_of_var_index"]
        [::std::mem::offset_of!(_YR_COMPILER, loop_for_of_var_index) - 740usize];
    ["Offset of field: _YR_COMPILER::file_name_stack"]
        [::std::mem::offset_of!(_YR_COMPILER, file_name_stack) - 744usize];
    ["Offset of field: _YR_COMPILER::file_name_stack_ptr"]
        [::std::mem::offset_of!(_YR_COMPILER, file_name_stack_ptr) - 872usize];
    ["Offset of field: _YR_COMPILER::last_error_extra_info"]
        [::std::mem::offset_of!(_YR_COMPILER, last_error_extra_info) - 876usize];
    ["Offset of field: _YR_COMPILER::lex_buf"]
        [::std::mem::offset_of!(_YR_COMPILER, lex_buf) - 1132usize];
    ["Offset of field: _YR_COMPILER::lex_buf_ptr"]
        [::std::mem::offset_of!(_YR_COMPILER, lex_buf_ptr) - 9328usize];
    ["Offset of field: _YR_COMPILER::lex_buf_len"]
        [::std::mem::offset_of!(_YR_COMPILER, lex_buf_len) - 9336usize];
    ["Offset of field: _YR_COMPILER::include_base_dir"]
        [::std::mem::offset_of!(_YR_COMPILER, include_base_dir) - 9338usize];
    ["Offset of field: _YR_COMPILER::user_data"]
        [::std::mem::offset_of!(_YR_COMPILER, user_data) - 13440usize];
    ["Offset of field: _YR_COMPILER::incl_clbk_user_data"]
        [::std::mem::offset_of!(_YR_COMPILER, incl_clbk_user_data) - 13448usize];
    ["Offset of field: _YR_COMPILER::re_ast_clbk_user_data"]
        [::std::mem::offset_of!(_YR_COMPILER, re_ast_clbk_user_data) - 13456usize];
    ["Offset of field: _YR_COMPILER::callback"]
        [::std::mem::offset_of!(_YR_COMPILER, callback) - 13464usize];
    ["Offset of field: _YR_COMPILER::include_callback"]
        [::std::mem::offset_of!(_YR_COMPILER, include_callback) - 13472usize];
    ["Offset of field: _YR_COMPILER::include_free"]
        [::std::mem::offset_of!(_YR_COMPILER, include_free) - 13480usize];
    ["Offset of field: _YR_COMPILER::re_ast_callback"]
        [::std::mem::offset_of!(_YR_COMPILER, re_ast_callback) - 13488usize];
    ["Offset of field: _YR_COMPILER::atoms_config"]
        [::std::mem::offset_of!(_YR_COMPILER, atoms_config) - 13496usize];
};
pub type YR_COMPILER = _YR_COMPILER;
unsafe extern "C" {
    pub fn yr_compiler_create(compiler: *mut *mut YR_COMPILER) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_destroy(compiler: *mut YR_COMPILER);
}
unsafe extern "C" {
    pub fn yr_compiler_set_callback(
        compiler: *mut YR_COMPILER,
        callback: YR_COMPILER_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn yr_compiler_set_include_callback(
        compiler: *mut YR_COMPILER,
        include_callback: YR_COMPILER_INCLUDE_CALLBACK_FUNC,
        include_free: YR_COMPILER_INCLUDE_FREE_FUNC,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn yr_compiler_set_re_ast_callback(
        compiler: *mut YR_COMPILER,
        re_ast_callback: YR_COMPILER_RE_AST_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn yr_compiler_set_atom_quality_table(
        compiler: *mut YR_COMPILER,
        table: *const ::std::os::raw::c_void,
        entries: ::std::os::raw::c_int,
        warning_threshold: ::std::os::raw::c_uchar,
    );
}
unsafe extern "C" {
    pub fn yr_compiler_load_atom_quality_table(
        compiler: *mut YR_COMPILER,
        filename: *const ::std::os::raw::c_char,
        warning_threshold: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_add_file(
        compiler: *mut YR_COMPILER,
        rules_file: *mut FILE,
        namespace_: *const ::std::os::raw::c_char,
        file_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_add_fd(
        compiler: *mut YR_COMPILER,
        rules_fd: ::std::os::raw::c_int,
        namespace_: *const ::std::os::raw::c_char,
        file_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_add_bytes(
        compiler: *mut YR_COMPILER,
        rules_data: *const ::std::os::raw::c_void,
        rules_size: size_t,
        namespace_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_add_string(
        compiler: *mut YR_COMPILER,
        rules_string: *const ::std::os::raw::c_char,
        namespace_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_get_error_message(
        compiler: *mut YR_COMPILER,
        buffer: *mut ::std::os::raw::c_char,
        buffer_size: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn yr_compiler_get_current_file_name(
        compiler: *mut YR_COMPILER,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn yr_compiler_define_integer_variable(
        compiler: *mut YR_COMPILER,
        identifier: *const ::std::os::raw::c_char,
        value: i64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_define_boolean_variable(
        compiler: *mut YR_COMPILER,
        identifier: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_define_float_variable(
        compiler: *mut YR_COMPILER,
        identifier: *const ::std::os::raw::c_char,
        value: f64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_define_string_variable(
        compiler: *mut YR_COMPILER,
        identifier: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_compiler_get_rules(
        compiler: *mut YR_COMPILER,
        rules: *mut *mut YR_RULES,
    ) -> ::std::os::raw::c_int;
}
pub const _YR_CONFIG_NAME_YR_CONFIG_STACK_SIZE: _YR_CONFIG_NAME = 0;
pub const _YR_CONFIG_NAME_YR_CONFIG_MAX_STRINGS_PER_RULE: _YR_CONFIG_NAME = 1;
pub const _YR_CONFIG_NAME_YR_CONFIG_MAX_MATCH_DATA: _YR_CONFIG_NAME = 2;
pub const _YR_CONFIG_NAME_YR_CONFIG_MAX_PROCESS_MEMORY_CHUNK: _YR_CONFIG_NAME = 3;
pub const _YR_CONFIG_NAME_YR_CONFIG_LAST: _YR_CONFIG_NAME = 4;
pub type _YR_CONFIG_NAME = ::std::os::raw::c_uint;
pub use self::_YR_CONFIG_NAME as YR_CONFIG_NAME;
unsafe extern "C" {
    pub fn yr_initialize() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_finalize() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_set_configuration_uint32(arg1: YR_CONFIG_NAME, arg2: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_set_configuration_uint64(arg1: YR_CONFIG_NAME, arg2: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_get_configuration_uint32(
        arg1: YR_CONFIG_NAME,
        arg2: *mut u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_get_configuration_uint64(
        arg1: YR_CONFIG_NAME,
        arg2: *mut u64,
    ) -> ::std::os::raw::c_int;
}
pub type YR_SCANNER = YR_SCAN_CONTEXT;
unsafe extern "C" {
    pub fn yr_scanner_create(
        rules: *mut YR_RULES,
        scanner: *mut *mut YR_SCANNER,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_destroy(scanner: *mut YR_SCANNER);
}
unsafe extern "C" {
    pub fn yr_scanner_set_callback(
        scanner: *mut YR_SCANNER,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn yr_scanner_set_timeout(scanner: *mut YR_SCANNER, timeout: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn yr_scanner_set_flags(scanner: *mut YR_SCANNER, flags: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn yr_scanner_define_integer_variable(
        scanner: *mut YR_SCANNER,
        identifier: *const ::std::os::raw::c_char,
        value: i64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_define_boolean_variable(
        scanner: *mut YR_SCANNER,
        identifier: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_define_float_variable(
        scanner: *mut YR_SCANNER,
        identifier: *const ::std::os::raw::c_char,
        value: f64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_define_string_variable(
        scanner: *mut YR_SCANNER,
        identifier: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_scan_mem_blocks(
        scanner: *mut YR_SCANNER,
        iterator: *mut YR_MEMORY_BLOCK_ITERATOR,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_scan_mem(
        scanner: *mut YR_SCANNER,
        buffer: *const u8,
        buffer_size: size_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_scan_file(
        scanner: *mut YR_SCANNER,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_scan_fd(
        scanner: *mut YR_SCANNER,
        fd: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_scan_proc(
        scanner: *mut YR_SCANNER,
        pid: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_scanner_last_error_rule(scanner: *mut YR_SCANNER) -> *mut YR_RULE;
}
unsafe extern "C" {
    pub fn yr_scanner_last_error_string(scanner: *mut YR_SCANNER) -> *mut YR_STRING;
}
unsafe extern "C" {
    pub fn yr_scanner_get_profiling_info(scanner: *mut YR_SCANNER) -> *mut YR_RULE_PROFILING_INFO;
}
unsafe extern "C" {
    pub fn yr_scanner_reset_profiling_info(scanner: *mut YR_SCANNER);
}
unsafe extern "C" {
    pub fn yr_scanner_print_profiling_info(scanner: *mut YR_SCANNER) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_scan_mem_blocks(
        rules: *mut YR_RULES,
        iterator: *mut YR_MEMORY_BLOCK_ITERATOR,
        flags: ::std::os::raw::c_int,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
        timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_scan_mem(
        rules: *mut YR_RULES,
        buffer: *const u8,
        buffer_size: size_t,
        flags: ::std::os::raw::c_int,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
        timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_scan_file(
        rules: *mut YR_RULES,
        filename: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
        timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_scan_fd(
        rules: *mut YR_RULES,
        fd: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
        timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_scan_proc(
        rules: *mut YR_RULES,
        pid: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
        callback: YR_CALLBACK_FUNC,
        user_data: *mut ::std::os::raw::c_void,
        timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_save(
        rules: *mut YR_RULES,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_save_stream(
        rules: *mut YR_RULES,
        stream: *mut YR_STREAM,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_load(
        filename: *const ::std::os::raw::c_char,
        rules: *mut *mut YR_RULES,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_load_stream(
        stream: *mut YR_STREAM,
        rules: *mut *mut YR_RULES,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_destroy(rules: *mut YR_RULES) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_define_integer_variable(
        rules: *mut YR_RULES,
        identifier: *const ::std::os::raw::c_char,
        value: i64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_define_boolean_variable(
        rules: *mut YR_RULES,
        identifier: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_define_float_variable(
        rules: *mut YR_RULES,
        identifier: *const ::std::os::raw::c_char,
        value: f64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_define_string_variable(
        rules: *mut YR_RULES,
        identifier: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rules_get_stats(
        rules: *mut YR_RULES,
        stats: *mut YR_RULES_STATS,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn yr_rule_disable(rule: *mut YR_RULE);
}
unsafe extern "C" {
    pub fn yr_rule_enable(rule: *mut YR_RULE);
}
unsafe extern "C" {
    pub fn yr_rules_from_arena(
        arena: *mut YR_ARENA,
        rules: *mut *mut YR_RULES,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct YR_MODULE_IMPORT {
    pub module_name: *const ::std::os::raw::c_char,
    pub module_data: *mut ::std::os::raw::c_void,
    pub module_data_size: size_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of YR_MODULE_IMPORT"][::std::mem::size_of::<YR_MODULE_IMPORT>() - 24usize];
    ["Alignment of YR_MODULE_IMPORT"][::std::mem::align_of::<YR_MODULE_IMPORT>() - 8usize];
    ["Offset of field: YR_MODULE_IMPORT::module_name"]
        [::std::mem::offset_of!(YR_MODULE_IMPORT, module_name) - 0usize];
    ["Offset of field: YR_MODULE_IMPORT::module_data"]
        [::std::mem::offset_of!(YR_MODULE_IMPORT, module_data) - 8usize];
    ["Offset of field: YR_MODULE_IMPORT::module_data_size"]
        [::std::mem::offset_of!(YR_MODULE_IMPORT, module_data_size) - 16usize];
};
